export enum commentsTypes {
    GET_ALL_COMMENTS = "GET_ALL_COMMENTS",
    GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS",
    GET_ALL_COMMENTS_FAILURE = "GET_ALL_COMMENTS_FAILURE",
    APPROVE_COMMENTS = "APPROVE_COMMENTS",
    APPROVE_COMMENTS_SUCCESS = "APPROVE_COMMENTS_SUCCESS",
    APPROVE_COMMENTS_FAILURE = "APPROVE_COMMENTS_FAILURE",
    DELETE_COMMENT = "DELETE_COMMENT",
    DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE",
  }
  