export enum commentsTypes {
    GET_ALL_COMMENTS = "GET_ALL_COMMENTS",
    GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS",
    GET_ALL_COMMENTS_FAILURE = "GET_ALL_COMMENTS_FAILURE",
    APPROVE_COMMENTS = "APPROVE_COMMENTS",
    APPROVE_COMMENTS_SUCCESS = "APPROVE_COMMENTS_SUCCESS",
    APPROVE_COMMENTS_FAILURE = "APPROVE_COMMENTS_FAILURE",
  }
  