export enum movieTypes {
    FETCH_MOVIES = "FETCH_MOVIES",
    FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS",
    FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE",
    GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID",
  }
  