export enum movieTypes {
    FETCH_MOVIES = "FETCH_MOVIES",
    FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS",
    FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE",
    FETCH_MOVIE_BY_ID = "FETCH_MOVIE_BY_ID",
    FETCH_MOVIE_BY_ID_SUCCESS = "FETCH_MOVIE_BY_ID_SUCCES",
    FETCH_MOVIE_BY_ID_FAILURE = "FETCH_MOVIE_BY_ID_FAILURE",
    CREATE_MOVIE = "CREATE_MOVIE",
    CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS ",
    CREATE_MOVIE_FAILURE = "CREATE_MOVIE_FAILURE "
  }
  