export enum ratingTypes {
    UPDATE_RATING = "UPDATE_RATING",
    UPDATE_RATING_SUCCESS = "UPDATE_RATING_SUCCESS",
    UPDATE_RATING_FAILURE = "UPDATE_RATING_FAILURE",
    FETCH_RATING = "FETCH_RATING",
    FETCH_RATING_SUCCESS = "FETCH_RATING_SUCCESS",
    FETCH_RATING_FAILURE = "FETCH_RATING_FAILURE",
}
  